### PR TITLE
Dockerfile - integrate npm dependencies installation into docker build process

### PR DESCRIPTION
**Pull request by nopoz**
Some changes to the Dockerfile so npm dependencies can be installed during the docker build process and don't need to be installed prior.

### CODE REVIEW

**Comment by fmartinou** [comment]
Hi,

It looks good to me 👍
I merge it to a feature branch to let Travis build it.

**Comment by fmartinou** [comment]
@nopoz 

Unfortunately your changes are breaking the build of the ARM images ([as you can see there](https://app.travis-ci.com/github/getwud/wud/builds/272934715?serverType=git)).

```
#13 [linux/arm/v7 ui-builder 3/5] RUN npm install
#13 651.8 npm warn deprecated rollup-plugin-terser@7.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser
#13 651.8 npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
#13 ...
#36 [linux/arm/v6 ui-builder 3/5] RUN npm install
#36 665.7 npm warn deprecated workbox-cacheable-response@6.6.0: workbox-background-sync@6.6.0
#36 ...
#54 [linux/arm64 ui-builder 3/5] RUN npm install
#54 667.1 npm warn deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
#54 670.7 npm warn deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
#54 675.7 npm warn deprecated rollup-plugin-terser@7.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser
#54 ...
#13 [linux/arm/v7 ui-builder 3/5] RUN npm install
#13 671.5 npm warn deprecated webpack-chain@6.5.1: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
#13 ...
#43 [linux/arm64 dependencies 2/2] RUN npm ci --omit=dev --omit=optional --n...
#43 685.3 npm error code ECONNRESET
#43 685.3 npm error errno ECONNRESET
#43 685.5 npm error network request to https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz failed, reason: Client network socket disconnected before secure TLS connection was established
#43 685.5 npm error network This is a problem related to network connectivity.
#43 685.5 npm error network In most cases you are behind a proxy or have bad network settings.
#43 685.5 npm error network
#43 685.5 npm error network If you are behind a proxy, please make sure that the
#43 685.5 npm error network 'proxy' config is set properly.  See: 'npm help config'
#43 685.6 
#43 685.6 npm error A complete log of this run can be found in: /root/.npm/_logs/2024-10-29T15_56_44_920Z-debug-0.log
#43 ERROR: process "/dev/.buildkit_qemu_emulator /bin/sh -c npm ci --omit=dev --omit=optional --no-audit --no-fund --no-update-notifier" did not complete successfully: exit code: 1
#13 [linux/arm/v7 ui-builder 3/5] RUN npm install
#13 ...
#54 [linux/arm64 ui-builder 3/5] RUN npm install
#54 CANCELED
#36 [linux/arm/v6 ui-builder 3/5] RUN npm install
#36 CANCELED
#13 [linux/arm/v7 ui-builder 3/5] RUN npm install
#13 CANCELED
------
 > [linux/arm64 dependencies 2/2] RUN npm ci --omit=dev --omit=optional --no-audit --no-fund --no-update-notifier:
------
failed to solve: rpc error: code = Unknown desc = process "/dev/.buildkit_qemu_emulator /bin/sh -c npm ci --omit=dev --omit=optional --no-audit --no-fund --no-update-notifier" did not complete successfully: exit code: 1
make: *** [Makefile:12: build] Error 1
```

**Comment by nopoz** [comment]
@fmartinou is it still failing to build? [That Travis CI link](https://app.travis-ci.com/github/getwud/wud/builds/272934715?serverType=git) in your comment looks like it passed? Sorry, I'm not super familar with Travis CI or building for ARM.

**Comment by fmartinou** [comment]
The task is not reported as failed for an obscure reaseon **but** the docker buildx command is failing.
(You  need to expand the last lines of the build to get the details)

It ends with a:
```
failed to solve: rpc error: code = Unknown desc = process "/dev/.buildkit_qemu_emulator /bin/sh -c npm ci --omit=dev --omit=optional --no-audit --no-fund --no-update-notifier" did not complete successfully: exit code: 1
make: *** [Makefile:12: build] Error 1
```
That's probably caused by the way `arm` images are built
(using [QEMU](https://www.qemu.org/) to allow buillding `arm` arch images from `amd64` machines).

**Pull request merged**
